Chapter06/bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Chapter06/bookmarks/images/urls.py
from django.urls import path
from .views import (
    image_create, image_detail, image_like, image_list, image_ranking
)

app_name = 'images'

urlpatterns = [
    path('create/', image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', image_detail, name='detail'),
    path('like/', image_like, name='like'),
    path('ranking/', image_ranking, name='image_ranking'),
    path('', image_list, name='list'),
]

Chapter06/bookmarks/images/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='images_created',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='images_liked',
        blank=True
    )
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

Chapter06/bookmarks/images/forms.py
from django import forms
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError(
                'The given URL does not match valid image extensions.'
            )
        return url

    def save(self, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'

        # download image
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)

        if commit:
            image.save()
        return image

Chapter06/bookmarks/images/views.py
import redis
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from .forms import ImageCreateForm
from .models import Image
from actions.utils import create_action
from common.decorators import ajax_required


r = redis.Redis(
    host=settings.REDIS_HOST,
    port=settings.REDIS_PORT,
    db=settings.REDIS_DB,
)


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')

            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(request.GET)
        return render(request, 'images/image/create.html', {
            'section': 'images',
            'form': form,
        })


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    is_liked = request.user in image.users_like.all()
    total_views = r.incr(f'image:{image.id}:views')
    r.zincrby('image_ranking', 1, image.id)
    return render(request, 'images/image/detail.html',  {
        'section': 'images',
        'image': image,
        'is_liked': is_liked,
        'total_views': total_views,
    })


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 2)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    context = {
        'section': 'images',
        'images': images,
    }
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', context)
    return render(request, 'images/image/list.html', context)


@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda image: image_ranking_ids.index(image.id))
    return render(request, 'images/image/ranking.html', {
        'section': 'images',
        'most_viewed': most_viewed,
    })

Chapter06/bookmarks/images/templates/images/image/create.html
{% extends '_base.html' %}

{% block title %}Bookmark an image{% endblock title %}
{% block content %}
  <h1>Bookmark an image</h1>
  <img class="image-preview" src="{{ request.GET.url }}" alt="image-preview">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Bookmark it!">
  </form>
{% endblock content %}

Chapter06/bookmarks/images/templates/images/image/detail.html
{% extends '_base.html' %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock title %}
{% block content %}
  <h1>{{ image.title }}</h1>
  <a href="{{ image.image.url }}">
    <img
      src="{% thumbnail image.image 300x0 quality=100 %}"
      alt="image"
      class="image-detail"
    >
  </a>
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes | pluralize }}
        </span>
        <span class="count">
          {{ total_views }} view{{ total_views | pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}"
          data-action="{% if is_liked %}un{% endif %}like"
          class="like button">
          {% if is_liked %}
            Unlike
          {% else %}
            Like
          {% endif %}
        </a>
      </div>
      {{ image.description | linebreaks }}
    </div>
    <div class="image-likes">
      <h4>Liked by:</h4>
      {% for user in users_like %}
      <div>
        {% if user.profile.photo %}
          <img src="{{ user.profile.photo.url }}" alt="user-profile-pic">
        {% endif %}
        <p>{{ forloop.counter }}. {{ user.first_name }}</p>
      </div>
      {% empty %}
        No likes yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock content %}

{% block domready %}
<script>
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}', {
      id: $(this).data('id'),
      action: $(this).data('action')
    }, function(data){
      if(data['status'] == 'ok') {
        // update dom
        var previous_action = $('a.like').data('action');
        console.log(previous_action);
        $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
        $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
        
        var previous_likes = parseInt($('span.count .total').text());
        $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
      }
    });
  });
</script>
{% endblock domready %}

Chapter06/bookmarks/images/templates/images/image/list.html
{% extends '_base.html' %}

{% block title %}Images bookmarked{% endblock title %}
{% block content %}
  <h1>Images bookmarked</h1>
  <div id="image-list">
    {% include 'images/image/list_ajax.html' %}
  </div>
{% endblock content %}

{% block domready %}
<script>
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function(){
    var margin = $(document).height() - $(window).height() - 200;
    if($(window).scrollTop() > margin && empty_page == false && block_request == false) {
      block_request = true;
      page += 1;
      $.get('?page=' + page, function(data){
        if(data == '') {
          empty_page = true;
        } else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
</script>
{% endblock domready %}

Chapter06/bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
  <div class="image" style="width: 100%;">
    <a href="{{ image.get_absolute_url }}">
      {% thumbnail image.image 300x0 crop='smart' as im %}
      <img src="{{ im.url }}" alt="image" st>
    </a>
    <div class="info">
      <a href="{{ image.get_absolute_url }}" class="title">
        {{ image.title }}
      </a>
    </div>
  </div>
{% endfor %}

Chapter06/bookmarks/images/templates/images/image/ranking.html
{% extends '_base.html' %}

{% block title %}Images ranking{% endblock title %}

{% block content %}
  <h1>Images ranking</h1>
  <ol>
    {% for image in most_viewed %}
      <li>
        <a href="{{ image.get_absolute_url }}">
          {{ image.title }}
        </a>
      </li>
    {% endfor %}
  </ol>
{% endblock content %}